"""持久化契约：结果引用、步骤检查点、JobRunView 与副作用恢复。

方案《结果存储、检查点与恢复（整合版）》的契约面，全部 backend-neutral：

* :mod:`~lumi_contracts.persistence.result_store`：统一 ``ResultRef`` 与分层/预算决策；
* :mod:`~lumi_contracts.persistence.checkpoint`：步骤状态机与落盘记录；
* :mod:`~lumi_contracts.persistence.run_view`：前端恢复用的有界快照；
* :mod:`~lumi_contracts.persistence.effect_recovery`：副作用三态 → 恢复动作。
"""

from __future__ import annotations

from lumi_contracts.persistence.checkpoint import (
    ALLOWED_TRANSITIONS,
    CHECKPOINT_CONTRACT_VERSION,
    CHECKPOINT_VERSION,
    PERSIST_THEN_EMIT_EVENTS,
    TERMINAL_STATES,
    CheckpointOrderingError,
    StepCheckpoint,
    StepCheckpointState,
    StepRuntimeStatus,
    assert_emit_after_persist,
    assert_transition,
    can_transition,
    checkpoint_is_stale,
    checkpoint_summary,
    merge_checkpoint,
    must_persist_before_emit,
    normalize_state,
    runtime_status_for,
    unfinished_steps,
    unresolved_side_effects,
)
from lumi_contracts.persistence.effect_recovery import (
    JOURNAL_CONFIRMED,
    JOURNAL_IN_FLIGHT,
    JOURNAL_INTENT,
    JOURNAL_PENDING,
    JOURNAL_UNCERTAIN,
    RecoveryAction,
    RecoveryPlan,
    StepRecoveryPlan,
    canonical_status,
    is_in_flight,
    plan_recovery,
)
from lumi_contracts.persistence.recovery_plan import (
    REASON_ALREADY_SETTLED,
    REASON_NEEDS_HUMAN,
    REASON_RESUME,
    RecoveryDecision,
    ResumePlan,
    StepPlan,
    plan_resume,
    reconciliation_targets,
    settle_reconciled_step,
)
from lumi_contracts.persistence.result_store import (
    INTEGRITY_ERROR_CODE,
    RESULT_REF_EXPIRED,
    RESULT_REF_FIELDS,
    RESULT_REF_FORBIDDEN,
    RESULT_REF_INTEGRITY_FAILED,
    RESULT_REF_SCHEMA_MISMATCH,
    RESULT_REF_UNAVAILABLE,
    BoundedLoad,
    LoadBudget,
    ResultBlobPort,
    ResultDegradation,
    ResultKvPort,
    ResultRef,
    ResultRefError,
    ResultStorageKind,
    StoredResult,
    TieringPolicy,
    bound_body,
    canonical_json,
    describe_ref,
    digest_bytes,
    expires_at_from_iso,
    expires_at_iso,
    ref_from_mapping,
    resolve_expiry,
    sequence_within_budget,
)
from lumi_contracts.persistence.run_view import (
    FINAL_ANSWER_MAX_CHARS,
    PROCESS_LOG_ENTRY_MAX_BYTES,
    PROCESS_LOG_MAX_ENTRIES,
    SNAPSHOT_MAX_BYTES,
    JobRunView,
    StepView,
    clip_utf8,
)

__all__ = [
    "ALLOWED_TRANSITIONS",
    "CHECKPOINT_CONTRACT_VERSION",
    "CHECKPOINT_VERSION",
    "FINAL_ANSWER_MAX_CHARS",
    "INTEGRITY_ERROR_CODE",
    "JOURNAL_CONFIRMED",
    "JOURNAL_IN_FLIGHT",
    "JOURNAL_INTENT",
    "JOURNAL_PENDING",
    "JOURNAL_UNCERTAIN",
    "PERSIST_THEN_EMIT_EVENTS",
    "PROCESS_LOG_ENTRY_MAX_BYTES",
    "PROCESS_LOG_MAX_ENTRIES",
    "REASON_ALREADY_SETTLED",
    "REASON_NEEDS_HUMAN",
    "REASON_RESUME",
    "RESULT_REF_EXPIRED",
    "RESULT_REF_FIELDS",
    "RESULT_REF_FORBIDDEN",
    "RESULT_REF_INTEGRITY_FAILED",
    "RESULT_REF_SCHEMA_MISMATCH",
    "RESULT_REF_UNAVAILABLE",
    "SNAPSHOT_MAX_BYTES",
    "TERMINAL_STATES",
    "BoundedLoad",
    "CheckpointOrderingError",
    "JobRunView",
    "LoadBudget",
    "RecoveryAction",
    "RecoveryDecision",
    "RecoveryPlan",
    "ResultBlobPort",
    "ResultDegradation",
    "ResultKvPort",
    "ResultRef",
    "ResultRefError",
    "ResultStorageKind",
    "ResumePlan",
    "StepCheckpoint",
    "StepCheckpointState",
    "StepRecoveryPlan",
    "StepPlan",
    "StepRuntimeStatus",
    "StepView",
    "StoredResult",
    "TieringPolicy",
    "assert_emit_after_persist",
    "assert_transition",
    "bound_body",
    "can_transition",
    "canonical_json",
    "canonical_status",
    "checkpoint_is_stale",
    "checkpoint_summary",
    "clip_utf8",
    "describe_ref",
    "digest_bytes",
    "expires_at_from_iso",
    "expires_at_iso",
    "is_in_flight",
    "merge_checkpoint",
    "must_persist_before_emit",
    "normalize_state",
    "plan_recovery",
    "plan_resume",
    "reconciliation_targets",
    "ref_from_mapping",
    "resolve_expiry",
    "runtime_status_for",
    "sequence_within_budget",
    "settle_reconciled_step",
    "unfinished_steps",
    "unresolved_side_effects",
]
