"""事件契约：流式事件、生命周期状态机、审批状态。"""

from __future__ import annotations

from lumi_contracts.events.approval import (
    ApprovalDecision,
    ApprovalScope,
    ApprovalState,
    approval_fingerprint,
)
from lumi_contracts.events.envelope import (
    CANONICAL_EVENT_TYPES,
    COMPAT_COMPANION_TYPES,
    EVENT_ENVELOPE_VERSION,
    LEGACY_EVENT_ALIASES,
    ApprovalRequiredPayload,
    ApprovalResolvedPayload,
    ArtifactCreatedPayload,
    CanonicalEventType,
    ControlPayload,
    ErrorPayload,
    EventEnvelope,
    ProcessPayload,
    StepCompletedPayload,
    StepStartedPayload,
    TextDeltaPayload,
    ViewUpdatedPayload,
    build_envelope,
    build_payload,
    bounded_opaque_value,
    canonical_event_type,
    canonical_events_for,
    dedupe_envelopes,
    is_canonical_event_type,
    make_event_id,
    strip_unsafe_payload,
)
from lumi_contracts.events.process import (
    ProcessKind,
    ProcessLogEntry,
    ProcessStatus,
    derive_kind,
    merge_process_log,
    sanitize_process_text,
)
from lumi_contracts.events.lifecycle import (
    TERMINAL_STATES,
    RunState,
    assert_transition,
    can_transition,
)
from lumi_contracts.events.stream import (
    KNOWN_EVENT_TYPES,
    EventSequencer,
    StreamEvent,
    StreamEventType,
)

__all__ = [
    "ApprovalDecision",
    "ApprovalRequiredPayload",
    "ApprovalResolvedPayload",
    "ApprovalScope",
    "ApprovalState",
    "ArtifactCreatedPayload",
    "CANONICAL_EVENT_TYPES",
    "COMPAT_COMPANION_TYPES",
    "CanonicalEventType",
    "ControlPayload",
    "EVENT_ENVELOPE_VERSION",
    "ErrorPayload",
    "EventEnvelope",
    "EventSequencer",
    "KNOWN_EVENT_TYPES",
    "LEGACY_EVENT_ALIASES",
    "ProcessKind",
    "ProcessLogEntry",
    "ProcessPayload",
    "ProcessStatus",
    "RunState",
    "StepCompletedPayload",
    "StepStartedPayload",
    "StreamEvent",
    "StreamEventType",
    "TERMINAL_STATES",
    "TextDeltaPayload",
    "ViewUpdatedPayload",
    "approval_fingerprint",
    "assert_transition",
    "build_envelope",
    "build_payload",
    "bounded_opaque_value",
    "can_transition",
    "canonical_event_type",
    "canonical_events_for",
    "dedupe_envelopes",
    "derive_kind",
    "is_canonical_event_type",
    "make_event_id",
    "merge_process_log",
    "sanitize_process_text",
    "strip_unsafe_payload",
]
